#pragma once

//****************************************************************************************
// Tbricks App API
//
// Copyright (c) 2019 Itiviti Group AB.
// Itiviti (R) is a registered trademark of Itiviti Group AB, Sweden. All rights reserved.
//
// TimeZoneID, represents time zone identifiers.
//****************************************************************************************

#define TZ_EAT TZ_STD_AFRICA_ADDIS_ABABA
#define TZ_WAT TZ_STD_AFRICA_BANGUI
#define TZ_CAT TZ_STD_AFRICA_BLANTYRE
#define TZ_EET TZ_STD_AFRICA_CAIRO
#define TZ_WET TZ_STD_AFRICA_CASABLANCA
#define TZ_SAST TZ_STD_AFRICA_JOHANNESBURG
#define TZ_AKST TZ_DST_AMERICA_ANCHORAGE
#define TZ_AST TZ_STD_AMERICA_ANGUILLA
#define TZ_BRT TZ_STD_AMERICA_ARAGUAINA
#define TZ_PYT TZ_DST_AMERICA_ASUNCION
#define TZ_AMT TZ_STD_AMERICA_BOA_VISTA
#define TZ_COT TZ_STD_AMERICA_BOGOTA
#define TZ_MST TZ_DST_AMERICA_BOISE
#define TZ_ARST TZ_STD_AMERICA_BUENOS_AIRES
#define TZ_VET TZ_STD_AMERICA_CARACAS
#define TZ_GFT TZ_STD_AMERICA_CAYENNE
#define TZ_EST TZ_STD_AMERICA_CAYMAN
#define TZ_PST TZ_DST_AMERICA_DAWSON
#define TZ_ACT TZ_STD_AMERICA_EIRUNEPE
#define TZ_WGT TZ_DST_AMERICA_GODTHAB
#define TZ_ECT TZ_STD_AMERICA_GUAYAQUIL
#define TZ_GYT TZ_STD_AMERICA_GUYANA
#define TZ_BOT TZ_STD_AMERICA_LA_PAZ
#define TZ_PET TZ_STD_AMERICA_LIMA
#define TZ_PMST TZ_DST_AMERICA_MIQUELON
#define TZ_UYT TZ_DST_AMERICA_MONTEVIDEO
#define TZ_FNT TZ_STD_AMERICA_NORONHA
#define TZ_SRT TZ_STD_AMERICA_PARAMARIBO
#define TZ_CLT TZ_STD_AMERICA_SANTIAGO
#define TZ_EGT TZ_DST_AMERICA_SCORESBYSUND
#define TZ_NST TZ_DST_AMERICA_ST_JOHNS
#define TZ_AWST TZ_STD_ANTARCTICA_CASEY
#define TZ_DAVT TZ_STD_ANTARCTICA_DAVIS
#define TZ_DDUT TZ_STD_ANTARCTICA_DUMONTDURVILLE
#define TZ_MAWT TZ_STD_ANTARCTICA_MAWSON
#define TZ_NZST TZ_DST_ANTARCTICA_MCMURDO
#define TZ_SYOT TZ_STD_ANTARCTICA_SYOWA
#define TZ_VOST TZ_STD_ANTARCTICA_VOSTOK
#define TZ_ALMT TZ_STD_ASIA_ALMATY
#define TZ_ANAT TZ_STD_ASIA_ANADYR
#define TZ_AQTT TZ_STD_ASIA_AQTAU
#define TZ_TMT TZ_STD_ASIA_ASHGABAT
#define TZ_AZT TZ_DST_ASIA_BAKU
#define TZ_ICT TZ_STD_ASIA_BANGKOK
#define TZ_KGT TZ_STD_ASIA_BISHKEK
#define TZ_BNT TZ_STD_ASIA_BRUNEI
#define TZ_IST TZ_STD_ASIA_CALCUTTA
#define TZ_CHOT TZ_DST_ASIA_CHOIBALSAN
#define TZ_BDT TZ_STD_ASIA_DHAKA
#define TZ_TLT TZ_STD_ASIA_DILI
#define TZ_GST TZ_STD_ASIA_DUBAI
#define TZ_TJT TZ_STD_ASIA_DUSHANBE
#define TZ_HKT TZ_STD_ASIA_HONG_KONG
#define TZ_HOVT TZ_DST_ASIA_HOVD
#define TZ_IRKT TZ_STD_ASIA_IRKUTSK
#define TZ_WIB TZ_STD_ASIA_JAKARTA
#define TZ_WIT TZ_STD_ASIA_JAYAPURA
#define TZ_AFT TZ_STD_ASIA_KABUL
#define TZ_PETT TZ_STD_ASIA_KAMCHATKA
#define TZ_PKST TZ_STD_ASIA_KARACHI
#define TZ_NPT TZ_STD_ASIA_KATMANDU
#define TZ_KRAT TZ_STD_ASIA_KRASNOYARSK
#define TZ_MYT TZ_STD_ASIA_KUALA_LUMPUR
#define TZ_MAGT TZ_STD_ASIA_MAGADAN
#define TZ_WITA TZ_STD_ASIA_MAKASSAR
#define TZ_PHT TZ_STD_ASIA_MANILA
#define TZ_NOVT TZ_STD_ASIA_NOVOSIBIRSK
#define TZ_OMST TZ_STD_ASIA_OMSK
#define TZ_KST TZ_STD_ASIA_PYONGYANG
#define TZ_MMT TZ_STD_ASIA_RANGOON
#define TZ_SAKT TZ_STD_ASIA_SAKHALIN
#define TZ_UZT TZ_STD_ASIA_SAMARKAND
#define TZ_SGT TZ_STD_ASIA_SINGAPORE
#define TZ_GET TZ_STD_ASIA_TBILISI
#define TZ_IRT TZ_STD_ASIA_TEHRAN
#define TZ_BTT TZ_STD_ASIA_THIMPHU
#define TZ_JDT TZ_STD_ASIA_TOKYO
#define TZ_ULAT TZ_DST_ASIA_ULAANBAATAR
#define TZ_VLAT TZ_STD_ASIA_VLADIVOSTOK
#define TZ_YAKT TZ_STD_ASIA_YAKUTSK
#define TZ_YEKT TZ_STD_ASIA_YEKATERINBURG
#define TZ_AZOT TZ_DST_ATLANTIC_AZORES
#define TZ_CVT TZ_STD_ATLANTIC_CAPE_VERDE
#define TZ_FKST TZ_STD_ATLANTIC_STANLEY
#define TZ_LHST TZ_DST_AUSTRALIA_LORD_HOWE
#define TZ_GMT TZ_DST_EUROPE_LONDON
#define TZ_MSK TZ_STD_EUROPE_MOSCOW
#define TZ_SAMT TZ_STD_EUROPE_SAMARA
#define TZ_CET TZ_DST_EUROPE_STOCKHOLM
#define TZ_IOT TZ_STD_INDIAN_CHAGOS
#define TZ_CXT TZ_STD_INDIAN_CHRISTMAS
#define TZ_CCT TZ_STD_INDIAN_COCOS
#define TZ_TFT TZ_STD_INDIAN_KERGUELEN
#define TZ_SCT TZ_STD_INDIAN_MAHE
#define TZ_MVT TZ_STD_INDIAN_MALDIVES
#define TZ_MUT TZ_STD_INDIAN_MAURITIUS
#define TZ_RET TZ_STD_INDIAN_REUNION
#define TZ_CHAST TZ_DST_PACIFIC_CHATHAM
#define TZ_EAST TZ_STD_PACIFIC_EASTER
#define TZ_VUST TZ_STD_PACIFIC_EFATE
#define TZ_PHOT TZ_STD_PACIFIC_ENDERBURY
#define TZ_TKT TZ_STD_PACIFIC_FAKAOFO
#define TZ_FJT TZ_DST_PACIFIC_FIJI
#define TZ_TVT TZ_STD_PACIFIC_FUNAFUTI
#define TZ_GALT TZ_STD_PACIFIC_GALAPAGOS
#define TZ_GAMT TZ_STD_PACIFIC_GAMBIER
#define TZ_SBT TZ_STD_PACIFIC_GUADALCANAL
#define TZ_CHST TZ_STD_PACIFIC_GUAM
#define TZ_HST TZ_STD_PACIFIC_HONOLULU
#define TZ_LINT TZ_STD_PACIFIC_KIRITIMATI
#define TZ_KOST TZ_STD_PACIFIC_KOSRAE
#define TZ_MHT TZ_STD_PACIFIC_KWAJALEIN
#define TZ_MART TZ_STD_PACIFIC_MARQUESAS
#define TZ_SST TZ_STD_PACIFIC_MIDWAY
#define TZ_NRT TZ_STD_PACIFIC_NAURU
#define TZ_NUT TZ_STD_PACIFIC_NIUE
#define TZ_NFT TZ_STD_PACIFIC_NORFOLK
#define TZ_NCT TZ_STD_PACIFIC_NOUMEA
#define TZ_PWT TZ_STD_PACIFIC_PALAU
#define TZ_PONT TZ_STD_PACIFIC_PONAPE
#define TZ_PGT TZ_STD_PACIFIC_PORT_MORESBY
#define TZ_CKHST TZ_STD_PACIFIC_RAROTONGA
#define TZ_TAHT TZ_STD_PACIFIC_TAHITI
#define TZ_GILT TZ_STD_PACIFIC_TARAWA
#define TZ_TOT TZ_STD_PACIFIC_TONGATAPU
#define TZ_CHUT TZ_STD_PACIFIC_TRUK
#define TZ_WAKT TZ_STD_PACIFIC_WAKE
#define TZ_WFT TZ_STD_PACIFIC_WALLIS
#define TZ_UTC TZ_STD_UNIVERSAL_TIME
#define TZ_CST TZ_DST_CST6CDT

// namespace tbricks
namespace tbricks {

const int g_std_time_bound = 32767;

enum TimeZoneID
{
    TZ_EMPTY = 0,

    TZ_DST_AFRICA_CEUTA = 15,
    TZ_DST_AFRICA_WINDHOEK = 52,
    TZ_DST_AMERICA_ADAK = 53,
    TZ_DST_AMERICA_ANCHORAGE = 54,
    TZ_DST_AMERICA_ASUNCION = 59,
    TZ_DST_AMERICA_BOISE = 65,
    TZ_DST_AMERICA_CAMBRIDGE_BAY = 67,
    TZ_DST_AMERICA_CHICAGO = 73,
    TZ_DST_AMERICA_CHIHUAHUA = 74,
    TZ_DST_AMERICA_CUIABA = 77,
    TZ_DST_AMERICA_DAWSON = 80,
    TZ_DST_AMERICA_DENVER = 82,
    TZ_DST_AMERICA_DETROIT = 83,
    TZ_DST_AMERICA_EDMONTON = 85,
    TZ_DST_AMERICA_GLACE_BAY = 89,
    TZ_DST_AMERICA_GODTHAB = 90,
    TZ_DST_AMERICA_GOOSE_BAY = 91,
    TZ_DST_AMERICA_HALIFAX = 98,
    TZ_DST_AMERICA_HAVANA = 99,
    TZ_DST_AMERICA_INDIANA_INDIANAPOLIS = 101,
    TZ_DST_AMERICA_INDIANA_KNOX = 102,
    TZ_DST_AMERICA_INDIANA_MARENGO = 103,
    TZ_DST_AMERICA_INDIANA_VEVAY = 104,
    TZ_DST_AMERICA_INDIANAPOLIS = 105,
    TZ_DST_AMERICA_INUVIK = 106,
    TZ_DST_AMERICA_IQALUIT = 107,
    TZ_DST_AMERICA_JUNEAU = 110,
    TZ_DST_AMERICA_KENTUCKY_LOUISVILLE = 111,
    TZ_DST_AMERICA_KENTUCKY_MONTICELLO = 112,
    TZ_DST_AMERICA_LOS_ANGELES = 115,
    TZ_DST_AMERICA_LOUISVILLE = 116,
    TZ_DST_AMERICA_MAZATLAN = 121,
    TZ_DST_AMERICA_MENOMINEE = 123,
    TZ_DST_AMERICA_MERIDA = 124,
    TZ_DST_AMERICA_MEXICO_CITY = 125,
    TZ_DST_AMERICA_MIQUELON = 126,
    TZ_DST_AMERICA_MONTERREY = 127,
    TZ_DST_AMERICA_MONTEVIDEO = 128,
    TZ_DST_AMERICA_MONTREAL = 129,
    TZ_DST_AMERICA_NASSAU = 131,
    TZ_DST_AMERICA_NEW_YORK = 132,
    TZ_DST_AMERICA_NIPIGON = 133,
    TZ_DST_AMERICA_NOME = 134,
    TZ_DST_AMERICA_NORTH_DAKOTA_CENTER = 136,
    TZ_DST_AMERICA_PANGNIRTUNG = 138,
    TZ_DST_AMERICA_PORT_AU_PRINCE = 141,
    TZ_DST_AMERICA_RAINY_RIVER = 145,
    TZ_DST_AMERICA_RANKIN_INLET = 146,
    TZ_DST_AMERICA_SAO_PAULO = 153,
    TZ_DST_AMERICA_SCORESBYSUND = 154,
    TZ_DST_AMERICA_SHIPROCK = 155,
    TZ_DST_AMERICA_ST_JOHNS = 156,
    TZ_DST_AMERICA_THULE = 163,
    TZ_DST_AMERICA_THUNDER_BAY = 164,
    TZ_DST_AMERICA_TIJUANA = 165,
    TZ_DST_AMERICA_VANCOUVER = 167,
    TZ_DST_AMERICA_WHITEHORSE = 168,
    TZ_DST_AMERICA_WINNIPEG = 169,
    TZ_DST_AMERICA_YAKUTAT = 170,
    TZ_DST_AMERICA_YELLOWKNIFE = 171,
    TZ_DST_ANTARCTICA_MCMURDO = 176,
    TZ_DST_ANTARCTICA_SOUTH_POLE = 178,
    TZ_DST_ARCTIC_LONGYEARBYEN = 181,
    TZ_DST_ASIA_AMMAN = 184,
    TZ_DST_ASIA_BAKU = 191,
    TZ_DST_ASIA_BEIRUT = 193,
    TZ_DST_ASIA_CHOIBALSAN = 197,
    TZ_DST_ASIA_DAMASCUS = 200,
    TZ_DST_ASIA_GAZA = 205,
    TZ_DST_ASIA_HOVD = 208,
    TZ_DST_ASIA_ISTANBUL = 210,
    TZ_DST_ASIA_JERUSALEM = 213,
    TZ_DST_ASIA_NICOSIA = 229,
    TZ_DST_ASIA_ULAANBAATAR = 253,
    TZ_DST_ATLANTIC_AZORES = 260,
    TZ_DST_ATLANTIC_BERMUDA = 261,
    TZ_DST_ATLANTIC_CANARY = 262,
    TZ_DST_ATLANTIC_FAEROE = 264,
    TZ_DST_ATLANTIC_JAN_MAYEN = 265,
    TZ_DST_ATLANTIC_MADEIRA = 266,
    TZ_DST_AUSTRALIA_ADELAIDE = 271,
    TZ_DST_AUSTRALIA_BROKEN_HILL = 273,
    TZ_DST_AUSTRALIA_HOBART = 275,
    TZ_DST_AUSTRALIA_LORD_HOWE = 277,
    TZ_DST_AUSTRALIA_MELBOURNE = 278,
    TZ_DST_AUSTRALIA_SYDNEY = 280,
    TZ_DST_EUROPE_AMSTERDAM = 281,
    TZ_DST_EUROPE_ANDORRA = 282,
    TZ_DST_EUROPE_ATHENS = 283,
    TZ_DST_EUROPE_BELFAST = 284,
    TZ_DST_EUROPE_BELGRADE = 285,
    TZ_DST_EUROPE_BERLIN = 286,
    TZ_DST_EUROPE_BRATISLAVA = 287,
    TZ_DST_EUROPE_BRUSSELS = 288,
    TZ_DST_EUROPE_BUCHAREST = 289,
    TZ_DST_EUROPE_BUDAPEST = 290,
    TZ_DST_EUROPE_CHISINAU = 291,
    TZ_DST_EUROPE_COPENHAGEN = 292,
    TZ_DST_EUROPE_DUBLIN = 293,
    TZ_DST_EUROPE_GIBRALTAR = 294,
    TZ_DST_EUROPE_HELSINKI = 295,
    TZ_DST_EUROPE_ISTANBUL = 296,
    TZ_DST_EUROPE_KIEV = 298,
    TZ_DST_EUROPE_LISBON = 299,
    TZ_DST_EUROPE_LJUBLJANA = 300,
    TZ_DST_EUROPE_LONDON = 301,
    TZ_DST_EUROPE_LUXEMBOURG = 302,
    TZ_DST_EUROPE_MADRID = 303,
    TZ_DST_EUROPE_MALTA = 304,
    TZ_DST_EUROPE_MONACO = 306,
    TZ_DST_EUROPE_NICOSIA = 308,
    TZ_DST_EUROPE_OSLO = 309,
    TZ_DST_EUROPE_PARIS = 310,
    TZ_DST_EUROPE_PRAGUE = 311,
    TZ_DST_EUROPE_RIGA = 312,
    TZ_DST_EUROPE_ROME = 313,
    TZ_DST_EUROPE_SAN_MARINO = 315,
    TZ_DST_EUROPE_SARAJEVO = 316,
    TZ_DST_EUROPE_SKOPJE = 318,
    TZ_DST_EUROPE_SOFIA = 319,
    TZ_DST_EUROPE_STOCKHOLM = 320,
    TZ_DST_EUROPE_TALLINN = 321,
    TZ_DST_EUROPE_TIRANE = 322,
    TZ_DST_EUROPE_UZHGOROD = 323,
    TZ_DST_EUROPE_VADUZ = 324,
    TZ_DST_EUROPE_VATICAN = 325,
    TZ_DST_EUROPE_VIENNA = 326,
    TZ_DST_EUROPE_VILNIUS = 327,
    TZ_DST_EUROPE_WARSAW = 328,
    TZ_DST_EUROPE_ZAGREB = 329,
    TZ_DST_EUROPE_ZAPOROZHYE = 330,
    TZ_DST_EUROPE_ZURICH = 331,
    TZ_DST_PACIFIC_APIA = 343,
    TZ_DST_PACIFIC_AUCKLAND = 344,
    TZ_DST_PACIFIC_CHATHAM = 345,
    TZ_DST_PACIFIC_FIJI = 350,
    TZ_DST_US_EASTERN = 383,
    TZ_DST_US_CENTRAL = 384,
    TZ_DST_AMERICA_INDIANA_VINCENNES = 385,
    TZ_DST_AUSTRALIA_CURRIE = 386,
    TZ_DST_AMERICA_NORTH_DAKOTA_NEW_SALEM = 387,
    TZ_DST_AMERICA_MATAMOROS = 389,
    TZ_DST_EUROPE_MARIEHAMN = 393,
    TZ_DST_ASIA_HEBRON = 394,
    TZ_DST_MST7MDT = 399,
    TZ_DST_AMERICA_BAHIA_BANDERAS = 401,
    TZ_DST_CST6CDT = 402,
    TZ_DST_PST8PDT = 409,
    TZ_DST_AMERICA_TORONTO = 413,
    TZ_DST_AMERICA_MONCTON = 415,
    TZ_DST_AMERICA_INDIANA_PETERSBURG = 416,
    TZ_DST_AMERICA_RESOLUTE = 419,
    TZ_DST_AMERICA_INDIANA_WINAMAC = 420,
    TZ_DST_AMERICA_SITKA = 426,
    TZ_DST_EST5EDT = 427,
    TZ_DST_AMERICA_OJINAGA = 430,
    TZ_DST_AMERICA_SANTA_ISABEL = 432,
    TZ_DST_AMERICA_CAMPO_GRANDE = 433,
    TZ_DST_ATLANTIC_FAROE = 435,
    TZ_DST_AMERICA_INDIANA_TELL_CITY = 437,
    TZ_DST_AMERICA_NORTH_DAKOTA_BEULAH = 439,
    TZ_DST_US_MICHIGAN = 441,
    TZ_DST_AMERICA_KNOX_IN = 445,
    TZ_DST_PORTUGAL = 446,
    TZ_DST_AUSTRALIA_SOUTH = 447,
    TZ_DST_EUROPE_JERSEY = 448,
    TZ_DST_TURKEY = 449,
    TZ_DST_AMERICA_ENSENADA = 450,
    TZ_DST_BRAZIL_EAST = 453,
    TZ_DST_CANADA_EASTERN = 455,
    TZ_DST_ISRAEL = 457,
    TZ_DST_EUROPE_PODGORICA = 458,
    TZ_DST_EUROPE_TIRASPOL = 460,
    TZ_DST_CANADA_YUKON = 462,
    TZ_DST_EUROPE_BUSINGEN = 465,
    TZ_DST_AUSTRALIA_YANCOWINNA = 468,
    TZ_DST_US_PACIFIC_NEW = 469,
    TZ_DST_EUROPE_ISLE_OF_MAN = 470,
    TZ_DST_EIRE = 471,
    TZ_DST_NZ_CHAT = 472,
    TZ_DST_CANADA_NEWFOUNDLAND = 473,
    TZ_DST_EUROPE_GUERNSEY = 474,
    TZ_DST_NAVAJO = 475,
    TZ_DST_AUSTRALIA_CANBERRA = 477,
    TZ_DST_AUSTRALIA_TASMANIA = 479,
    TZ_DST_AUSTRALIA_VICTORIA = 481,
    TZ_DST_NZ = 482,
    TZ_DST_GB = 484,
    TZ_DST_US_MOUNTAIN = 485,
    TZ_DST_US_ALEUTIAN = 486,
    TZ_DST_MEXICO_BAJANORTE = 487,
    TZ_DST_AMERICA_ATKA = 490,
    TZ_DST_AUSTRALIA_LHI = 491,
    TZ_DST_MEXICO_BAJASUR = 495,
    TZ_DST_US_EAST_INDIANA = 496,
    TZ_DST_CANADA_CENTRAL = 499,
    TZ_DST_POLAND = 501,
    TZ_DST_CUBA = 503,
    TZ_DST_CANADA_ATLANTIC = 505,
    TZ_DST_CANADA_PACIFIC = 508,
    TZ_DST_MEXICO_GENERAL = 509,
    TZ_DST_US_ALASKA = 513,
    TZ_DST_AUSTRALIA_ACT = 515,
    TZ_DST_CANADA_MOUNTAIN = 516,
    TZ_DST_ASIA_ULAN_BATOR = 518,
    TZ_DST_AUSTRALIA_NSW = 520,
    TZ_DST_GB_EIRE = 521,
    TZ_DST_AMERICA_FORT_WAYNE = 523,
    TZ_DST_US_INDIANA_STARKE = 524,
    TZ_DST_US_PACIFIC = 526,
    TZ_DST_ASIA_TEL_AVIV = 527,

    // standard time identifiers
    TZ_STD_AFRICA_ABIDJAN = (g_std_time_bound + 1),
    TZ_STD_AFRICA_ACCRA = (g_std_time_bound + 2),
    TZ_STD_AFRICA_ADDIS_ABABA = (g_std_time_bound + 3),
    TZ_STD_AFRICA_ALGIERS = (g_std_time_bound + 4),
    TZ_STD_AFRICA_ASMERA = (g_std_time_bound + 5),
    TZ_STD_AFRICA_BAMAKO = (g_std_time_bound + 6),
    TZ_STD_AFRICA_BANGUI = (g_std_time_bound + 7),
    TZ_STD_AFRICA_BANJUL = (g_std_time_bound + 8),
    TZ_STD_AFRICA_BISSAU = (g_std_time_bound + 9),
    TZ_STD_AFRICA_BLANTYRE = (g_std_time_bound + 10),
    TZ_STD_AFRICA_BRAZZAVILLE = (g_std_time_bound + 11),
    TZ_STD_AFRICA_BUJUMBURA = (g_std_time_bound + 12),
    TZ_STD_AFRICA_CAIRO = (g_std_time_bound + 13),
    TZ_STD_AFRICA_CASABLANCA = (g_std_time_bound + 14),
    TZ_STD_AFRICA_CEUTA = (g_std_time_bound + 15),
    TZ_STD_AFRICA_CONAKRY = (g_std_time_bound + 16),
    TZ_STD_AFRICA_DAKAR = (g_std_time_bound + 17),
    TZ_STD_AFRICA_DAR_ES_SALAAM = (g_std_time_bound + 18),
    TZ_STD_AFRICA_DJIBOUTI = (g_std_time_bound + 19),
    TZ_STD_AFRICA_DOUALA = (g_std_time_bound + 20),
    TZ_STD_AFRICA_EL_AAIUN = (g_std_time_bound + 21),
    TZ_STD_AFRICA_FREETOWN = (g_std_time_bound + 22),
    TZ_STD_AFRICA_GABORONE = (g_std_time_bound + 23),
    TZ_STD_AFRICA_HARARE = (g_std_time_bound + 24),
    TZ_STD_AFRICA_JOHANNESBURG = (g_std_time_bound + 25),
    TZ_STD_AFRICA_KAMPALA = (g_std_time_bound + 26),
    TZ_STD_AFRICA_KHARTOUM = (g_std_time_bound + 27),
    TZ_STD_AFRICA_KIGALI = (g_std_time_bound + 28),
    TZ_STD_AFRICA_KINSHASA = (g_std_time_bound + 29),
    TZ_STD_AFRICA_LAGOS = (g_std_time_bound + 30),
    TZ_STD_AFRICA_LIBREVILLE = (g_std_time_bound + 31),
    TZ_STD_AFRICA_LOME = (g_std_time_bound + 32),
    TZ_STD_AFRICA_LUANDA = (g_std_time_bound + 33),
    TZ_STD_AFRICA_LUBUMBASHI = (g_std_time_bound + 34),
    TZ_STD_AFRICA_LUSAKA = (g_std_time_bound + 35),
    TZ_STD_AFRICA_MALABO = (g_std_time_bound + 36),
    TZ_STD_AFRICA_MAPUTO = (g_std_time_bound + 37),
    TZ_STD_AFRICA_MASERU = (g_std_time_bound + 38),
    TZ_STD_AFRICA_MBABANE = (g_std_time_bound + 39),
    TZ_STD_AFRICA_MOGADISHU = (g_std_time_bound + 40),
    TZ_STD_AFRICA_MONROVIA = (g_std_time_bound + 41),
    TZ_STD_AFRICA_NAIROBI = (g_std_time_bound + 42),
    TZ_STD_AFRICA_NDJAMENA = (g_std_time_bound + 43),
    TZ_STD_AFRICA_NIAMEY = (g_std_time_bound + 44),
    TZ_STD_AFRICA_NOUAKCHOTT = (g_std_time_bound + 45),
    TZ_STD_AFRICA_OUAGADOUGOU = (g_std_time_bound + 46),
    TZ_STD_AFRICA_PORTO_NOVO = (g_std_time_bound + 47),
    TZ_STD_AFRICA_SAO_TOME = (g_std_time_bound + 48),
    TZ_STD_AFRICA_TIMBUKTU = (g_std_time_bound + 49),
    TZ_STD_AFRICA_TRIPOLI = (g_std_time_bound + 50),
    TZ_STD_AFRICA_TUNIS = (g_std_time_bound + 51),
    TZ_STD_AFRICA_WINDHOEK = (g_std_time_bound + 52),
    TZ_STD_AMERICA_ADAK = (g_std_time_bound + 53),
    TZ_STD_AMERICA_ANCHORAGE = (g_std_time_bound + 54),
    TZ_STD_AMERICA_ANGUILLA = (g_std_time_bound + 55),
    TZ_STD_AMERICA_ANTIGUA = (g_std_time_bound + 56),
    TZ_STD_AMERICA_ARAGUAINA = (g_std_time_bound + 57),
    TZ_STD_AMERICA_ARUBA = (g_std_time_bound + 58),
    TZ_STD_AMERICA_ASUNCION = (g_std_time_bound + 59),
    TZ_STD_AMERICA_BARBADOS = (g_std_time_bound + 60),
    TZ_STD_AMERICA_BELEM = (g_std_time_bound + 61),
    TZ_STD_AMERICA_BELIZE = (g_std_time_bound + 62),
    TZ_STD_AMERICA_BOA_VISTA = (g_std_time_bound + 63),
    TZ_STD_AMERICA_BOGOTA = (g_std_time_bound + 64),
    TZ_STD_AMERICA_BOISE = (g_std_time_bound + 65),
    TZ_STD_AMERICA_BUENOS_AIRES = (g_std_time_bound + 66),
    TZ_STD_AMERICA_CAMBRIDGE_BAY = (g_std_time_bound + 67),
    TZ_STD_AMERICA_CANCUN = (g_std_time_bound + 68),
    TZ_STD_AMERICA_CARACAS = (g_std_time_bound + 69),
    TZ_STD_AMERICA_CATAMARCA = (g_std_time_bound + 70),
    TZ_STD_AMERICA_CAYENNE = (g_std_time_bound + 71),
    TZ_STD_AMERICA_CAYMAN = (g_std_time_bound + 72),
    TZ_STD_AMERICA_CHICAGO = (g_std_time_bound + 73),
    TZ_STD_AMERICA_CHIHUAHUA = (g_std_time_bound + 74),
    TZ_STD_AMERICA_CORDOBA = (g_std_time_bound + 75),
    TZ_STD_AMERICA_COSTA_RICA = (g_std_time_bound + 76),
    TZ_STD_AMERICA_CUIABA = (g_std_time_bound + 77),
    TZ_STD_AMERICA_CURACAO = (g_std_time_bound + 78),
    TZ_STD_AMERICA_DANMARKSHAVN = (g_std_time_bound + 79),
    TZ_STD_AMERICA_DAWSON = (g_std_time_bound + 80),
    TZ_STD_AMERICA_DAWSON_CREEK = (g_std_time_bound + 81),
    TZ_STD_AMERICA_DENVER = (g_std_time_bound + 82),
    TZ_STD_AMERICA_DETROIT = (g_std_time_bound + 83),
    TZ_STD_AMERICA_DOMINICA = (g_std_time_bound + 84),
    TZ_STD_AMERICA_EDMONTON = (g_std_time_bound + 85),
    TZ_STD_AMERICA_EIRUNEPE = (g_std_time_bound + 86),
    TZ_STD_AMERICA_EL_SALVADOR = (g_std_time_bound + 87),
    TZ_STD_AMERICA_FORTALEZA = (g_std_time_bound + 88),
    TZ_STD_AMERICA_GLACE_BAY = (g_std_time_bound + 89),
    TZ_STD_AMERICA_GODTHAB = (g_std_time_bound + 90),
    TZ_STD_AMERICA_GOOSE_BAY = (g_std_time_bound + 91),
    TZ_STD_AMERICA_GRAND_TURK = (g_std_time_bound + 92),
    TZ_STD_AMERICA_GRENADA = (g_std_time_bound + 93),
    TZ_STD_AMERICA_GUADELOUPE = (g_std_time_bound + 94),
    TZ_STD_AMERICA_GUATEMALA = (g_std_time_bound + 95),
    TZ_STD_AMERICA_GUAYAQUIL = (g_std_time_bound + 96),
    TZ_STD_AMERICA_GUYANA = (g_std_time_bound + 97),
    TZ_STD_AMERICA_HALIFAX = (g_std_time_bound + 98),
    TZ_STD_AMERICA_HAVANA = (g_std_time_bound + 99),
    TZ_STD_AMERICA_HERMOSILLO = (g_std_time_bound + 100),
    TZ_STD_AMERICA_INDIANA_INDIANAPOLIS = (g_std_time_bound + 101),
    TZ_STD_AMERICA_INDIANA_KNOX = (g_std_time_bound + 102),
    TZ_STD_AMERICA_INDIANA_MARENGO = (g_std_time_bound + 103),
    TZ_STD_AMERICA_INDIANA_VEVAY = (g_std_time_bound + 104),
    TZ_STD_AMERICA_INDIANAPOLIS = (g_std_time_bound + 105),
    TZ_STD_AMERICA_INUVIK = (g_std_time_bound + 106),
    TZ_STD_AMERICA_IQALUIT = (g_std_time_bound + 107),
    TZ_STD_AMERICA_JAMAICA = (g_std_time_bound + 108),
    TZ_STD_AMERICA_JUJUY = (g_std_time_bound + 109),
    TZ_STD_AMERICA_JUNEAU = (g_std_time_bound + 110),
    TZ_STD_AMERICA_KENTUCKY_LOUISVILLE = (g_std_time_bound + 111),
    TZ_STD_AMERICA_KENTUCKY_MONTICELLO = (g_std_time_bound + 112),
    TZ_STD_AMERICA_LA_PAZ = (g_std_time_bound + 113),
    TZ_STD_AMERICA_LIMA = (g_std_time_bound + 114),
    TZ_STD_AMERICA_LOS_ANGELES = (g_std_time_bound + 115),
    TZ_STD_AMERICA_LOUISVILLE = (g_std_time_bound + 116),
    TZ_STD_AMERICA_MACEIO = (g_std_time_bound + 117),
    TZ_STD_AMERICA_MANAGUA = (g_std_time_bound + 118),
    TZ_STD_AMERICA_MANAUS = (g_std_time_bound + 119),
    TZ_STD_AMERICA_MARTINIQUE = (g_std_time_bound + 120),
    TZ_STD_AMERICA_MAZATLAN = (g_std_time_bound + 121),
    TZ_STD_AMERICA_MENDOZA = (g_std_time_bound + 122),
    TZ_STD_AMERICA_MENOMINEE = (g_std_time_bound + 123),
    TZ_STD_AMERICA_MERIDA = (g_std_time_bound + 124),
    TZ_STD_AMERICA_MEXICO_CITY = (g_std_time_bound + 125),
    TZ_STD_AMERICA_MIQUELON = (g_std_time_bound + 126),
    TZ_STD_AMERICA_MONTERREY = (g_std_time_bound + 127),
    TZ_STD_AMERICA_MONTEVIDEO = (g_std_time_bound + 128),
    TZ_STD_AMERICA_MONTREAL = (g_std_time_bound + 129),
    TZ_STD_AMERICA_MONTSERRAT = (g_std_time_bound + 130),
    TZ_STD_AMERICA_NASSAU = (g_std_time_bound + 131),
    TZ_STD_AMERICA_NEW_YORK = (g_std_time_bound + 132),
    TZ_STD_AMERICA_NIPIGON = (g_std_time_bound + 133),
    TZ_STD_AMERICA_NOME = (g_std_time_bound + 134),
    TZ_STD_AMERICA_NORONHA = (g_std_time_bound + 135),
    TZ_STD_AMERICA_NORTH_DAKOTA_CENTER = (g_std_time_bound + 136),
    TZ_STD_AMERICA_PANAMA = (g_std_time_bound + 137),
    TZ_STD_AMERICA_PANGNIRTUNG = (g_std_time_bound + 138),
    TZ_STD_AMERICA_PARAMARIBO = (g_std_time_bound + 139),
    TZ_STD_AMERICA_PHOENIX = (g_std_time_bound + 140),
    TZ_STD_AMERICA_PORT_AU_PRINCE = (g_std_time_bound + 141),
    TZ_STD_AMERICA_PORT_OF_SPAIN = (g_std_time_bound + 142),
    TZ_STD_AMERICA_PORTO_VELHO = (g_std_time_bound + 143),
    TZ_STD_AMERICA_PUERTO_RICO = (g_std_time_bound + 144),
    TZ_STD_AMERICA_RAINY_RIVER = (g_std_time_bound + 145),
    TZ_STD_AMERICA_RANKIN_INLET = (g_std_time_bound + 146),
    TZ_STD_AMERICA_RECIFE = (g_std_time_bound + 147),
    TZ_STD_AMERICA_REGINA = (g_std_time_bound + 148),
    TZ_STD_AMERICA_RIO_BRANCO = (g_std_time_bound + 149),
    TZ_STD_AMERICA_ROSARIO = (g_std_time_bound + 150),
    TZ_STD_AMERICA_SANTIAGO = (g_std_time_bound + 151),
    TZ_STD_AMERICA_SANTO_DOMINGO = (g_std_time_bound + 152),
    TZ_STD_AMERICA_SAO_PAULO = (g_std_time_bound + 153),
    TZ_STD_AMERICA_SCORESBYSUND = (g_std_time_bound + 154),
    TZ_STD_AMERICA_SHIPROCK = (g_std_time_bound + 155),
    TZ_STD_AMERICA_ST_JOHNS = (g_std_time_bound + 156),
    TZ_STD_AMERICA_ST_KITTS = (g_std_time_bound + 157),
    TZ_STD_AMERICA_ST_LUCIA = (g_std_time_bound + 158),
    TZ_STD_AMERICA_ST_THOMAS = (g_std_time_bound + 159),
    TZ_STD_AMERICA_ST_VINCENT = (g_std_time_bound + 160),
    TZ_STD_AMERICA_SWIFT_CURRENT = (g_std_time_bound + 161),
    TZ_STD_AMERICA_TEGUCIGALPA = (g_std_time_bound + 162),
    TZ_STD_AMERICA_THULE = (g_std_time_bound + 163),
    TZ_STD_AMERICA_THUNDER_BAY = (g_std_time_bound + 164),
    TZ_STD_AMERICA_TIJUANA = (g_std_time_bound + 165),
    TZ_STD_AMERICA_TORTOLA = (g_std_time_bound + 166),
    TZ_STD_AMERICA_VANCOUVER = (g_std_time_bound + 167),
    TZ_STD_AMERICA_WHITEHORSE = (g_std_time_bound + 168),
    TZ_STD_AMERICA_WINNIPEG = (g_std_time_bound + 169),
    TZ_STD_AMERICA_YAKUTAT = (g_std_time_bound + 170),
    TZ_STD_AMERICA_YELLOWKNIFE = (g_std_time_bound + 171),
    TZ_STD_ANTARCTICA_CASEY = (g_std_time_bound + 172),
    TZ_STD_ANTARCTICA_DAVIS = (g_std_time_bound + 173),
    TZ_STD_ANTARCTICA_DUMONTDURVILLE = (g_std_time_bound + 174),
    TZ_STD_ANTARCTICA_MAWSON = (g_std_time_bound + 175),
    TZ_STD_ANTARCTICA_MCMURDO = (g_std_time_bound + 176),
    TZ_STD_ANTARCTICA_PALMER = (g_std_time_bound + 177),
    TZ_STD_ANTARCTICA_SOUTH_POLE = (g_std_time_bound + 178),
    TZ_STD_ANTARCTICA_SYOWA = (g_std_time_bound + 179),
    TZ_STD_ANTARCTICA_VOSTOK = (g_std_time_bound + 180),
    TZ_STD_ARCTIC_LONGYEARBYEN = (g_std_time_bound + 181),
    TZ_STD_ASIA_ADEN = (g_std_time_bound + 182),
    TZ_STD_ASIA_ALMATY = (g_std_time_bound + 183),
    TZ_STD_ASIA_AMMAN = (g_std_time_bound + 184),
    TZ_STD_ASIA_ANADYR = (g_std_time_bound + 185),
    TZ_STD_ASIA_AQTAU = (g_std_time_bound + 186),
    TZ_STD_ASIA_AQTOBE = (g_std_time_bound + 187),
    TZ_STD_ASIA_ASHGABAT = (g_std_time_bound + 188),
    TZ_STD_ASIA_BAGHDAD = (g_std_time_bound + 189),
    TZ_STD_ASIA_BAHRAIN = (g_std_time_bound + 190),
    TZ_STD_ASIA_BAKU = (g_std_time_bound + 191),
    TZ_STD_ASIA_BANGKOK = (g_std_time_bound + 192),
    TZ_STD_ASIA_BEIRUT = (g_std_time_bound + 193),
    TZ_STD_ASIA_BISHKEK = (g_std_time_bound + 194),
    TZ_STD_ASIA_BRUNEI = (g_std_time_bound + 195),
    TZ_STD_ASIA_CALCUTTA = (g_std_time_bound + 196),
    TZ_STD_ASIA_CHOIBALSAN = (g_std_time_bound + 197),
    TZ_STD_ASIA_CHONGQING = (g_std_time_bound + 198),
    TZ_STD_ASIA_COLOMBO = (g_std_time_bound + 199),
    TZ_STD_ASIA_DAMASCUS = (g_std_time_bound + 200),
    TZ_STD_ASIA_DHAKA = (g_std_time_bound + 201),
    TZ_STD_ASIA_DILI = (g_std_time_bound + 202),
    TZ_STD_ASIA_DUBAI = (g_std_time_bound + 203),
    TZ_STD_ASIA_DUSHANBE = (g_std_time_bound + 204),
    TZ_STD_ASIA_GAZA = (g_std_time_bound + 205),
    TZ_STD_ASIA_HARBIN = (g_std_time_bound + 206),
    TZ_STD_ASIA_HONG_KONG = (g_std_time_bound + 207),
    TZ_STD_ASIA_HOVD = (g_std_time_bound + 208),
    TZ_STD_ASIA_IRKUTSK = (g_std_time_bound + 209),
    TZ_STD_ASIA_ISTANBUL = (g_std_time_bound + 210),
    TZ_STD_ASIA_JAKARTA = (g_std_time_bound + 211),
    TZ_STD_ASIA_JAYAPURA = (g_std_time_bound + 212),
    TZ_STD_ASIA_JERUSALEM = (g_std_time_bound + 213),
    TZ_STD_ASIA_KABUL = (g_std_time_bound + 214),
    TZ_STD_ASIA_KAMCHATKA = (g_std_time_bound + 215),
    TZ_STD_ASIA_KARACHI = (g_std_time_bound + 216),
    TZ_STD_ASIA_KASHGAR = (g_std_time_bound + 217),
    TZ_STD_ASIA_KATMANDU = (g_std_time_bound + 218),
    TZ_STD_ASIA_KRASNOYARSK = (g_std_time_bound + 219),
    TZ_STD_ASIA_KUALA_LUMPUR = (g_std_time_bound + 220),
    TZ_STD_ASIA_KUCHING = (g_std_time_bound + 221),
    TZ_STD_ASIA_KUWAIT = (g_std_time_bound + 222),
    TZ_STD_ASIA_MACAO = (g_std_time_bound + 223),
    TZ_STD_ASIA_MACAU = (g_std_time_bound + 224),
    TZ_STD_ASIA_MAGADAN = (g_std_time_bound + 225),
    TZ_STD_ASIA_MAKASSAR = (g_std_time_bound + 226),
    TZ_STD_ASIA_MANILA = (g_std_time_bound + 227),
    TZ_STD_ASIA_MUSCAT = (g_std_time_bound + 228),
    TZ_STD_ASIA_NICOSIA = (g_std_time_bound + 229),
    TZ_STD_ASIA_NOVOSIBIRSK = (g_std_time_bound + 230),
    TZ_STD_ASIA_OMSK = (g_std_time_bound + 231),
    TZ_STD_ASIA_ORAL = (g_std_time_bound + 232),
    TZ_STD_ASIA_PHNOM_PENH = (g_std_time_bound + 233),
    TZ_STD_ASIA_PONTIANAK = (g_std_time_bound + 234),
    TZ_STD_ASIA_PYONGYANG = (g_std_time_bound + 235),
    TZ_STD_ASIA_QYZYLORDA = (g_std_time_bound + 236),
    TZ_STD_ASIA_QATAR = (g_std_time_bound + 237),
    TZ_STD_ASIA_RANGOON = (g_std_time_bound + 238),
    TZ_STD_ASIA_RIYADH = (g_std_time_bound + 239),
    TZ_STD_ASIA_SAIGON = (g_std_time_bound + 240),
    TZ_STD_ASIA_SAKHALIN = (g_std_time_bound + 241),
    TZ_STD_ASIA_SAMARKAND = (g_std_time_bound + 242),
    TZ_STD_ASIA_SEOUL = (g_std_time_bound + 243),
    TZ_STD_ASIA_SHANGHAI = (g_std_time_bound + 244),
    TZ_STD_ASIA_SINGAPORE = (g_std_time_bound + 245),
    TZ_STD_ASIA_TAIPEI = (g_std_time_bound + 246),
    TZ_STD_ASIA_TASHKENT = (g_std_time_bound + 247),
    TZ_STD_ASIA_TBILISI = (g_std_time_bound + 248),
    TZ_STD_ASIA_TEHRAN = (g_std_time_bound + 249),
    TZ_STD_ASIA_THIMPHU = (g_std_time_bound + 250),
    TZ_STD_ASIA_TOKYO = (g_std_time_bound + 251),
    TZ_STD_ASIA_UJUNG_PANDANG = (g_std_time_bound + 252),
    TZ_STD_ASIA_ULAANBAATAR = (g_std_time_bound + 253),
    TZ_STD_ASIA_URUMQI = (g_std_time_bound + 254),
    TZ_STD_ASIA_VIENTIANE = (g_std_time_bound + 255),
    TZ_STD_ASIA_VLADIVOSTOK = (g_std_time_bound + 256),
    TZ_STD_ASIA_YAKUTSK = (g_std_time_bound + 257),
    TZ_STD_ASIA_YEKATERINBURG = (g_std_time_bound + 258),
    TZ_STD_ASIA_YEREVAN = (g_std_time_bound + 259),
    TZ_STD_ATLANTIC_AZORES = (g_std_time_bound + 260),
    TZ_STD_ATLANTIC_BERMUDA = (g_std_time_bound + 261),
    TZ_STD_ATLANTIC_CANARY = (g_std_time_bound + 262),
    TZ_STD_ATLANTIC_CAPE_VERDE = (g_std_time_bound + 263),
    TZ_STD_ATLANTIC_FAEROE = (g_std_time_bound + 264),
    TZ_STD_ATLANTIC_JAN_MAYEN = (g_std_time_bound + 265),
    TZ_STD_ATLANTIC_MADEIRA = (g_std_time_bound + 266),
    TZ_STD_ATLANTIC_REYKJAVIK = (g_std_time_bound + 267),
    TZ_STD_ATLANTIC_SOUTH_GEORGIA = (g_std_time_bound + 268),
    TZ_STD_ATLANTIC_ST_HELENA = (g_std_time_bound + 269),
    TZ_STD_ATLANTIC_STANLEY = (g_std_time_bound + 270),
    TZ_STD_AUSTRALIA_ADELAIDE = (g_std_time_bound + 271),
    TZ_STD_AUSTRALIA_BRISBANE = (g_std_time_bound + 272),
    TZ_STD_AUSTRALIA_BROKEN_HILL = (g_std_time_bound + 273),
    TZ_STD_AUSTRALIA_DARWIN = (g_std_time_bound + 274),
    TZ_STD_AUSTRALIA_HOBART = (g_std_time_bound + 275),
    TZ_STD_AUSTRALIA_LINDEMAN = (g_std_time_bound + 276),
    TZ_STD_AUSTRALIA_LORD_HOWE = (g_std_time_bound + 277),
    TZ_STD_AUSTRALIA_MELBOURNE = (g_std_time_bound + 278),
    TZ_STD_AUSTRALIA_PERTH = (g_std_time_bound + 279),
    TZ_STD_AUSTRALIA_SYDNEY = (g_std_time_bound + 280),
    TZ_STD_EUROPE_AMSTERDAM = (g_std_time_bound + 281),
    TZ_STD_EUROPE_ANDORRA = (g_std_time_bound + 282),
    TZ_STD_EUROPE_ATHENS = (g_std_time_bound + 283),
    TZ_STD_EUROPE_BELFAST = (g_std_time_bound + 284),
    TZ_STD_EUROPE_BELGRADE = (g_std_time_bound + 285),
    TZ_STD_EUROPE_BERLIN = (g_std_time_bound + 286),
    TZ_STD_EUROPE_BRATISLAVA = (g_std_time_bound + 287),
    TZ_STD_EUROPE_BRUSSELS = (g_std_time_bound + 288),
    TZ_STD_EUROPE_BUCHAREST = (g_std_time_bound + 289),
    TZ_STD_EUROPE_BUDAPEST = (g_std_time_bound + 290),
    TZ_STD_EUROPE_CHISINAU = (g_std_time_bound + 291),
    TZ_STD_EUROPE_COPENHAGEN = (g_std_time_bound + 292),
    TZ_STD_EUROPE_DUBLIN = (g_std_time_bound + 293),
    TZ_STD_EUROPE_GIBRALTAR = (g_std_time_bound + 294),
    TZ_STD_EUROPE_HELSINKI = (g_std_time_bound + 295),
    TZ_STD_EUROPE_ISTANBUL = (g_std_time_bound + 296),
    TZ_STD_EUROPE_KALININGRAD = (g_std_time_bound + 297),
    TZ_STD_EUROPE_KIEV = (g_std_time_bound + 298),
    TZ_STD_EUROPE_LISBON = (g_std_time_bound + 299),
    TZ_STD_EUROPE_LJUBLJANA = (g_std_time_bound + 300),
    TZ_STD_EUROPE_LONDON = (g_std_time_bound + 301),
    TZ_STD_EUROPE_LUXEMBOURG = (g_std_time_bound + 302),
    TZ_STD_EUROPE_MADRID = (g_std_time_bound + 303),
    TZ_STD_EUROPE_MALTA = (g_std_time_bound + 304),
    TZ_STD_EUROPE_MINSK = (g_std_time_bound + 305),
    TZ_STD_EUROPE_MONACO = (g_std_time_bound + 306),
    TZ_STD_EUROPE_MOSCOW = (g_std_time_bound + 307),
    TZ_STD_EUROPE_NICOSIA = (g_std_time_bound + 308),
    TZ_STD_EUROPE_OSLO = (g_std_time_bound + 309),
    TZ_STD_EUROPE_PARIS = (g_std_time_bound + 310),
    TZ_STD_EUROPE_PRAGUE = (g_std_time_bound + 311),
    TZ_STD_EUROPE_RIGA = (g_std_time_bound + 312),
    TZ_STD_EUROPE_ROME = (g_std_time_bound + 313),
    TZ_STD_EUROPE_SAMARA = (g_std_time_bound + 314),
    TZ_STD_EUROPE_SAN_MARINO = (g_std_time_bound + 315),
    TZ_STD_EUROPE_SARAJEVO = (g_std_time_bound + 316),
    TZ_STD_EUROPE_SIMFEROPOL = (g_std_time_bound + 317),
    TZ_STD_EUROPE_SKOPJE = (g_std_time_bound + 318),
    TZ_STD_EUROPE_SOFIA = (g_std_time_bound + 319),
    TZ_STD_EUROPE_STOCKHOLM = (g_std_time_bound + 320),
    TZ_STD_EUROPE_TALLINN = (g_std_time_bound + 321),
    TZ_STD_EUROPE_TIRANE = (g_std_time_bound + 322),
    TZ_STD_EUROPE_UZHGOROD = (g_std_time_bound + 323),
    TZ_STD_EUROPE_VADUZ = (g_std_time_bound + 324),
    TZ_STD_EUROPE_VATICAN = (g_std_time_bound + 325),
    TZ_STD_EUROPE_VIENNA = (g_std_time_bound + 326),
    TZ_STD_EUROPE_VILNIUS = (g_std_time_bound + 327),
    TZ_STD_EUROPE_WARSAW = (g_std_time_bound + 328),
    TZ_STD_EUROPE_ZAGREB = (g_std_time_bound + 329),
    TZ_STD_EUROPE_ZAPOROZHYE = (g_std_time_bound + 330),
    TZ_STD_EUROPE_ZURICH = (g_std_time_bound + 331),
    TZ_STD_INDIAN_ANTANANARIVO = (g_std_time_bound + 332),
    TZ_STD_INDIAN_CHAGOS = (g_std_time_bound + 333),
    TZ_STD_INDIAN_CHRISTMAS = (g_std_time_bound + 334),
    TZ_STD_INDIAN_COCOS = (g_std_time_bound + 335),
    TZ_STD_INDIAN_COMORO = (g_std_time_bound + 336),
    TZ_STD_INDIAN_KERGUELEN = (g_std_time_bound + 337),
    TZ_STD_INDIAN_MAHE = (g_std_time_bound + 338),
    TZ_STD_INDIAN_MALDIVES = (g_std_time_bound + 339),
    TZ_STD_INDIAN_MAURITIUS = (g_std_time_bound + 340),
    TZ_STD_INDIAN_MAYOTTE = (g_std_time_bound + 341),
    TZ_STD_INDIAN_REUNION = (g_std_time_bound + 342),
    TZ_STD_PACIFIC_APIA = (g_std_time_bound + 343),
    TZ_STD_PACIFIC_AUCKLAND = (g_std_time_bound + 344),
    TZ_STD_PACIFIC_CHATHAM = (g_std_time_bound + 345),
    TZ_STD_PACIFIC_EASTER = (g_std_time_bound + 346),
    TZ_STD_PACIFIC_EFATE = (g_std_time_bound + 347),
    TZ_STD_PACIFIC_ENDERBURY = (g_std_time_bound + 348),
    TZ_STD_PACIFIC_FAKAOFO = (g_std_time_bound + 349),
    TZ_STD_PACIFIC_FIJI = (g_std_time_bound + 350),
    TZ_STD_PACIFIC_FUNAFUTI = (g_std_time_bound + 351),
    TZ_STD_PACIFIC_GALAPAGOS = (g_std_time_bound + 352),
    TZ_STD_PACIFIC_GAMBIER = (g_std_time_bound + 353),
    TZ_STD_PACIFIC_GUADALCANAL = (g_std_time_bound + 354),
    TZ_STD_PACIFIC_GUAM = (g_std_time_bound + 355),
    TZ_STD_PACIFIC_HONOLULU = (g_std_time_bound + 356),
    TZ_STD_PACIFIC_JOHNSTON = (g_std_time_bound + 357),
    TZ_STD_PACIFIC_KIRITIMATI = (g_std_time_bound + 358),
    TZ_STD_PACIFIC_KOSRAE = (g_std_time_bound + 359),
    TZ_STD_PACIFIC_KWAJALEIN = (g_std_time_bound + 360),
    TZ_STD_PACIFIC_MAJURO = (g_std_time_bound + 361),
    TZ_STD_PACIFIC_MARQUESAS = (g_std_time_bound + 362),
    TZ_STD_PACIFIC_MIDWAY = (g_std_time_bound + 363),
    TZ_STD_PACIFIC_NAURU = (g_std_time_bound + 364),
    TZ_STD_PACIFIC_NIUE = (g_std_time_bound + 365),
    TZ_STD_PACIFIC_NORFOLK = (g_std_time_bound + 366),
    TZ_STD_PACIFIC_NOUMEA = (g_std_time_bound + 367),
    TZ_STD_PACIFIC_PAGO_PAGO = (g_std_time_bound + 368),
    TZ_STD_PACIFIC_PALAU = (g_std_time_bound + 369),
    TZ_STD_PACIFIC_PITCAIRN = (g_std_time_bound + 370),
    TZ_STD_PACIFIC_PONAPE = (g_std_time_bound + 371),
    TZ_STD_PACIFIC_PORT_MORESBY = (g_std_time_bound + 372),
    TZ_STD_PACIFIC_RAROTONGA = (g_std_time_bound + 373),
    TZ_STD_PACIFIC_SAIPAN = (g_std_time_bound + 374),
    TZ_STD_PACIFIC_TAHITI = (g_std_time_bound + 375),
    TZ_STD_PACIFIC_TARAWA = (g_std_time_bound + 376),
    TZ_STD_PACIFIC_TONGATAPU = (g_std_time_bound + 377),
    TZ_STD_PACIFIC_TRUK = (g_std_time_bound + 378),
    TZ_STD_PACIFIC_WAKE = (g_std_time_bound + 379),
    TZ_STD_PACIFIC_WALLIS = (g_std_time_bound + 380),
    TZ_STD_PACIFIC_YAP = (g_std_time_bound + 381),
    TZ_STD_UNIVERSAL_TIME = (g_std_time_bound + 382),
    TZ_STD_US_EASTERN = (g_std_time_bound + 383),
    TZ_STD_US_CENTRAL = (g_std_time_bound + 384),
    TZ_STD_AMERICA_INDIANA_VINCENNES = (g_std_time_bound + 385),
    TZ_STD_AUSTRALIA_CURRIE = (g_std_time_bound + 386),
    TZ_STD_AMERICA_NORTH_DAKOTA_NEW_SALEM = (g_std_time_bound + 387),
    TZ_STD_AMERICA_BAHIA = (g_std_time_bound + 388),
    TZ_STD_AMERICA_MATAMOROS = (g_std_time_bound + 389),
    TZ_STD_AMERICA_ATIKOKAN = (g_std_time_bound + 390),
    TZ_STD_PACIFIC_POHNPEI = (g_std_time_bound + 391),
    TZ_STD_AMERICA_BLANC_SABLON = (g_std_time_bound + 392),
    TZ_STD_EUROPE_MARIEHAMN = (g_std_time_bound + 393),
    TZ_STD_ASIA_HEBRON = (g_std_time_bound + 394),
    TZ_STD_AMERICA_SANTAREM = (g_std_time_bound + 395),
    TZ_STD_AMERICA_ARGENTINA_MENDOZA = (g_std_time_bound + 396),
    TZ_STD_AMERICA_ARGENTINA_CORDOBA = (g_std_time_bound + 397),
    TZ_STD_PACIFIC_BOUGAINVILLE = (g_std_time_bound + 398),
    TZ_STD_MST7MDT = (g_std_time_bound + 399),
    TZ_STD_ASIA_HO_CHI_MINH = (g_std_time_bound + 400),
    TZ_STD_AMERICA_BAHIA_BANDERAS = (g_std_time_bound + 401),
    TZ_STD_CST6CDT = (g_std_time_bound + 402),
    TZ_STD_AMERICA_CRESTON = (g_std_time_bound + 403),
    TZ_STD_ASIA_KOLKATA = (g_std_time_bound + 404),
    TZ_STD_AMERICA_ARGENTINA_RIO_GALLEGOS = (g_std_time_bound + 405),
    TZ_STD_PACIFIC_CHUUK = (g_std_time_bound + 406),
    TZ_STD_ASIA_SREDNEKOLYMSK = (g_std_time_bound + 407),
    TZ_STD_AMERICA_ARGENTINA_LA_RIOJA = (g_std_time_bound + 408),
    TZ_STD_PST8PDT = (g_std_time_bound + 409),
    TZ_STD_AMERICA_ARGENTINA_SALTA = (g_std_time_bound + 410),
    TZ_STD_AMERICA_ARGENTINA_SAN_JUAN = (g_std_time_bound + 411),
    TZ_STD_ASIA_NOVOKUZNETSK = (g_std_time_bound + 412),
    TZ_STD_AMERICA_TORONTO = (g_std_time_bound + 413),
    TZ_STD_AUSTRALIA_EUCLA = (g_std_time_bound + 414),
    TZ_STD_AMERICA_MONCTON = (g_std_time_bound + 415),
    TZ_STD_AMERICA_INDIANA_PETERSBURG = (g_std_time_bound + 416),
    TZ_STD_ANTARCTICA_MACQUARIE = (g_std_time_bound + 417),
    TZ_STD_ASIA_UST_NERA = (g_std_time_bound + 418),
    TZ_STD_AMERICA_RESOLUTE = (g_std_time_bound + 419),
    TZ_STD_AMERICA_INDIANA_WINAMAC = (g_std_time_bound + 420),
    TZ_STD_ASIA_CHITA = (g_std_time_bound + 421),
    TZ_STD_AMERICA_ARGENTINA_JUJUY = (g_std_time_bound + 422),
    TZ_STD_AMERICA_ARGENTINA_TUCUMAN = (g_std_time_bound + 423),
    TZ_STD_EUROPE_VOLGOGRAD = (g_std_time_bound + 424),
    TZ_STD_ASIA_KHANDYGA = (g_std_time_bound + 425),
    TZ_STD_AMERICA_SITKA = (g_std_time_bound + 426),
    TZ_STD_EST5EDT = (g_std_time_bound + 427),
    TZ_STD_ASIA_KATHMANDU = (g_std_time_bound + 428),
    TZ_STD_AMERICA_ARGENTINA_CATAMARCA = (g_std_time_bound + 429),
    TZ_STD_AMERICA_OJINAGA = (g_std_time_bound + 430),
    TZ_STD_AMERICA_ARGENTINA_SAN_LUIS = (g_std_time_bound + 431),
    TZ_STD_AMERICA_SANTA_ISABEL = (g_std_time_bound + 432),
    TZ_STD_AMERICA_CAMPO_GRANDE = (g_std_time_bound + 433),
    TZ_STD_AMERICA_METLAKATLA = (g_std_time_bound + 434),
    TZ_STD_ATLANTIC_FAROE = (g_std_time_bound + 435),
    TZ_STD_AMERICA_ARGENTINA_BUENOS_AIRES = (g_std_time_bound + 436),
    TZ_STD_AMERICA_INDIANA_TELL_CITY = (g_std_time_bound + 437),
    TZ_STD_AMERICA_ARGENTINA_USHUAIA = (g_std_time_bound + 438),
    TZ_STD_AMERICA_NORTH_DAKOTA_BEULAH = (g_std_time_bound + 439),
    TZ_STD_ANTARCTICA_ROTHERA = (g_std_time_bound + 440),
    TZ_STD_US_MICHIGAN = (g_std_time_bound + 441),
    TZ_STD_AMERICA_MARIGOT = (g_std_time_bound + 442),
    TZ_STD_PACIFIC_SAMOA = (g_std_time_bound + 443),
    TZ_STD_AMERICA_CORAL_HARBOUR = (g_std_time_bound + 444),
    TZ_STD_AMERICA_KNOX_IN = (g_std_time_bound + 445),
    TZ_STD_PORTUGAL = (g_std_time_bound + 446),
    TZ_STD_AUSTRALIA_SOUTH = (g_std_time_bound + 447),
    TZ_STD_EUROPE_JERSEY = (g_std_time_bound + 448),
    TZ_STD_TURKEY = (g_std_time_bound + 449),
    TZ_STD_AMERICA_ENSENADA = (g_std_time_bound + 450),
    TZ_STD_AFRICA_ASMARA = (g_std_time_bound + 451),
    TZ_STD_JAPAN = (g_std_time_bound + 452),
    TZ_STD_BRAZIL_EAST = (g_std_time_bound + 453),
    TZ_STD_CANADA_SASKATCHEWAN = (g_std_time_bound + 454),
    TZ_STD_CANADA_EASTERN = (g_std_time_bound + 455),
    TZ_STD_JAMAICA = (g_std_time_bound + 456),
    TZ_STD_ISRAEL = (g_std_time_bound + 457),
    TZ_STD_EUROPE_PODGORICA = (g_std_time_bound + 458),
    TZ_STD_US_SAMOA = (g_std_time_bound + 459),
    TZ_STD_EUROPE_TIRASPOL = (g_std_time_bound + 460),
    TZ_STD_AUSTRALIA_NORTH = (g_std_time_bound + 461),
    TZ_STD_CANADA_YUKON = (g_std_time_bound + 462),
    TZ_STD_BRAZIL_WEST = (g_std_time_bound + 464),
    TZ_STD_EUROPE_BUSINGEN = (g_std_time_bound + 465),
    TZ_STD_SINGAPORE = (g_std_time_bound + 466),
    TZ_STD_US_HAWAII = (g_std_time_bound + 467),
    TZ_STD_AUSTRALIA_YANCOWINNA = (g_std_time_bound + 468),
    TZ_STD_US_PACIFIC_NEW = (g_std_time_bound + 469),
    TZ_STD_EUROPE_ISLE_OF_MAN = (g_std_time_bound + 470),
    TZ_STD_EIRE = (g_std_time_bound + 471),
    TZ_STD_NZ_CHAT = (g_std_time_bound + 472),
    TZ_STD_CANADA_NEWFOUNDLAND = (g_std_time_bound + 473),
    TZ_STD_EUROPE_GUERNSEY = (g_std_time_bound + 474),
    TZ_STD_NAVAJO = (g_std_time_bound + 475),
    TZ_STD_AUSTRALIA_WEST = (g_std_time_bound + 476),
    TZ_STD_AUSTRALIA_CANBERRA = (g_std_time_bound + 477),
    TZ_STD_LIBYA = (g_std_time_bound + 478),
    TZ_STD_AUSTRALIA_TASMANIA = (g_std_time_bound + 479),
    TZ_STD_AMERICA_PORTO_ACRE = (g_std_time_bound + 480),
    TZ_STD_AUSTRALIA_VICTORIA = (g_std_time_bound + 481),
    TZ_STD_NZ = (g_std_time_bound + 482),
    TZ_STD_HONGKONG = (g_std_time_bound + 483),
    TZ_STD_GB = (g_std_time_bound + 484),
    TZ_STD_US_MOUNTAIN = (g_std_time_bound + 485),
    TZ_STD_US_ALEUTIAN = (g_std_time_bound + 486),
    TZ_STD_MEXICO_BAJANORTE = (g_std_time_bound + 487),
    TZ_STD_ASIA_ASHKHABAD = (g_std_time_bound + 488),
    TZ_STD_AUSTRALIA_QUEENSLAND = (g_std_time_bound + 489),
    TZ_STD_AMERICA_ATKA = (g_std_time_bound + 490),
    TZ_STD_AUSTRALIA_LHI = (g_std_time_bound + 491),
    TZ_STD_BRAZIL_DENORONHA = (g_std_time_bound + 492),
    TZ_STD_AMERICA_KRALENDIJK = (g_std_time_bound + 493),
    TZ_STD_ICELAND = (g_std_time_bound + 494),
    TZ_STD_MEXICO_BAJASUR = (g_std_time_bound + 495),
    TZ_STD_US_EAST_INDIANA = (g_std_time_bound + 496),
    TZ_STD_AMERICA_LOWER_PRINCES = (g_std_time_bound + 497),
    TZ_STD_AFRICA_JUBA = (g_std_time_bound + 498),
    TZ_STD_CANADA_CENTRAL = (g_std_time_bound + 499),
    TZ_STD_AMERICA_ST_BARTHELEMY = (g_std_time_bound + 500),
    TZ_STD_POLAND = (g_std_time_bound + 501),
    TZ_STD_KWAJALEIN = (g_std_time_bound + 502),
    TZ_STD_CUBA = (g_std_time_bound + 503),
    TZ_STD_W_SU = (g_std_time_bound + 504),
    TZ_STD_CANADA_ATLANTIC = (g_std_time_bound + 505),
    TZ_STD_BRAZIL_ACRE = (g_std_time_bound + 506),
    TZ_STD_ASIA_CHUNGKING = (g_std_time_bound + 507),
    TZ_STD_CANADA_PACIFIC = (g_std_time_bound + 508),
    TZ_STD_MEXICO_GENERAL = (g_std_time_bound + 509),
    TZ_STD_AMERICA_VIRGIN = (g_std_time_bound + 510),
    TZ_STD_AMERICA_ARGENTINA_COMODRIVADAVIA = (g_std_time_bound + 511),
    TZ_STD_ASIA_THIMBU = (g_std_time_bound + 512),
    TZ_STD_US_ALASKA = (g_std_time_bound + 513),
    TZ_STD_ASIA_DACCA = (g_std_time_bound + 514),
    TZ_STD_AUSTRALIA_ACT = (g_std_time_bound + 515),
    TZ_STD_CANADA_MOUNTAIN = (g_std_time_bound + 516),
    TZ_STD_PRC = (g_std_time_bound + 517),
    TZ_STD_ASIA_ULAN_BATOR = (g_std_time_bound + 518),
    TZ_STD_US_ARIZONA = (g_std_time_bound + 519),
    TZ_STD_AUSTRALIA_NSW = (g_std_time_bound + 520),
    TZ_STD_GB_EIRE = (g_std_time_bound + 521),
    TZ_STD_ROK = (g_std_time_bound + 522),
    TZ_STD_AMERICA_FORT_WAYNE = (g_std_time_bound + 523),
    TZ_STD_US_INDIANA_STARKE = (g_std_time_bound + 524),
    TZ_STD_ROC = (g_std_time_bound + 525),
    TZ_STD_US_PACIFIC = (g_std_time_bound + 526),
    TZ_STD_ASIA_TEL_AVIV = (g_std_time_bound + 527),
    TZ_STD_CHILE_CONTINENTAL = (g_std_time_bound + 528),
    TZ_STD_CHILE_EASTERISLAND = (g_std_time_bound + 529),
    TZ_STD_EGYPT = (g_std_time_bound + 530),
    TZ_STD_AMERICA_FORT_NELSON = (g_std_time_bound + 531)
};

} // namespace tbricks
