Tbricks App API: tbricks::BinaryTableBuilder::UpdateCell
BinaryTableBuilder
BinaryTableBuilder
BinaryTableBuilder
Clear
ClearCell
ClearCell
Empty
GetTable
GetTable
operator=
operator=
Print
UpdateCell
UpdateCell
UpdateRow
~BinaryTableBuilder
UpdateCell() [1/2]
void UpdateCell (const DefinitionBase & def, const Uuid & row_id, const AnyType & value) inline
Updates the value of a cell in the table.
Parameters
def The parameter definition of the column of the cell to update
row_id The row of the cell to update
value The new value
Definition at line 230 of file BinaryTable.h.
References DefinitionBase::GetIdentifier(), and BinaryTableBuilder::UpdateCell().
Referenced by BinaryTableBuilder::UpdateCell().